version: '3.9'

services:
  db-postgres:
    image: postgres
    container_name: db-postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    hostname: database
    volumes:
      - ./multiple-databases.sh:/docker-entrypoint-initdb.d/multiple-databases.sh
    environment:
      POSTGRES_MULTIPLE_DATABASES: users, vendas
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.2
    container_name: keycloak
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 7080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://database:5432/users
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:7080/health/ready"
        ]
      interval: 15s
      timeout: 2s
      retries: 15
    command:
      [
        "start-dev",
        "--http-port 7080",
        "--https-port 7443",
        "--import-realm"
      ]
    #volumes:
    #  - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - 7080:7080
      - 7443:7443
    depends_on:
      - db-postgres
