spring:
  application:
    name: Vendas
  security:
    oauth2:
      client:
        provider:
          vendas:
            issuer-uri: http://localhost:7080/realms/vendas
        registration:
          vendas:
            provider: vendas
            client-name: login-app
            client-id: login-app
            client-secret: d6ghhMPXbJxZNGbXYpvA7NQlGAbdNhiR
            scope:
              - openid
              - offline_access
              - profile
              - microprofile-jwt
              - roles
            authorization-grant-type: authorization_code
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:7080/realms/vendas/protocol/openid-connect/certs
  datasource:
    url: jdbc:postgresql://${DATABASE_URL:localhost}:5432/vendas
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  messages:
    encoding: UTF-8
logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
server:
  port: ${PORT:3000}
